name: Promotion

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create report directory
        run: mkdir -p ./reports

      - name: Update version
        run: |
          VER=$(node -e "console.log(require('./package.json').version.replace(/-[0-9]+/, '-$GITHUB_RUN_NUMBER'))")
          echo "$VER" > ./version.txt
          if (echo $VER | egrep -- '-[0-9]+$' 1> /dev/null); then
            npm version $VER --no-git-tag-version
          fi

      - name: Lint
        run: npm run lint

      - name: Unit tests and coverage
        run: npm run test-coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: error

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
          if-no-files-found: error
